import status from "http-status";
import z from "zod";
import { TErrorResponse, TErrorSources } from "../interfaces/error.interface";

/**
 * handleZodError is a function that takes a ZodError object as an argument and returns a standardized error response object.
 *
 * It processes the validation errors generated by Zod and formats them into a consistent structure for easier handling in the application.
 */

export const handleZodError = (err: z.ZodError): TErrorResponse => {
  const statusCode = status.BAD_REQUEST;
  const message = "Zod Validation Error";

  //! The sources of the error are extracted from the ZodError object and stored in an array of TErrorSources, which includes the path to the error and the error message.
  const errorSources: TErrorSources[] = [];

  err.issues.forEach((issue) => {
    //! Pushing the Path and Message of the error into the errorSources array, where the path is joined with " => " to create a readable format for nested errors.
    errorSources.push({
      path: issue.path.join(" => "),
      message: issue.message,
    });
  });

  // Struturing the ZOD error response in a consistent format with success status, message, error sources, and HTTP status code for easier handling in the application.
  return {
    success: false,
    message,
    errorSources,
    statusCode,
  };
};
